import { fromStream, Zip } from '@zenfs/archives';
import { configureSingle, fs } from '@zenfs/core';
// @ts-expect-error 7016
import { setupLogs } from '@zenfs/core/tests/logs.js';
import assert from 'node:assert/strict';
import { fstatSync, readFileSync, readSync } from 'node:fs';
import { open } from 'node:fs/promises';
import { suite, test } from 'node:test';

setupLogs();

function _runTests() {
	test('readdir /', () => {
		assert.equal(fs.readdirSync('/').length, 3);
	});

	test('read /one.txt', () => {
		assert.equal(fs.readFileSync('/one.txt', 'utf8'), '1');
	});

	test('read /two.txt', () => {
		assert.equal(fs.readFileSync('/two.txt', 'utf8'), 'two');
	});

	test('readdir /nested', () => {
		assert.equal(fs.readdirSync('/nested').length, 1);
	});

	test('read /nested/omg.txt', () => {
		assert.equal(fs.readFileSync('/nested/omg.txt', 'utf8'), 'This is a nested file!');
	});
}

suite('Basic ZIP operations', () => {
	test('Configure', async () => {
		const buffer = readFileSync(import.meta.dirname + '/files/data.zip');
		const data = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
		await configureSingle({ backend: Zip, data });
	});

	_runTests();
});

await suite('ZIP case fold', {}, () => {
	test('Configure', async () => {
		const buffer = readFileSync(import.meta.dirname + '/files/data.zip');
		const data = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
		await configureSingle({ backend: Zip, data, caseFold: 'upper' });
	});

	test('read /ONES.TXT', () => {
		assert.equal(fs.readFileSync('/ONE.TXT', 'utf8'), '1');
	});

	test('read /NESTED/OMG.TXT', () => {
		assert.equal(fs.readFileSync('/NESTED/OMG.TXT', 'utf8'), 'This is a nested file!');
	});

	test('readdir /NESTED', () => {
		assert.equal(fs.readdirSync('/NESTED').length, 1);
	});

	test('read /nested/omg.txt (all lower)', () => {
		assert.equal(fs.readFileSync('/nested/omg.txt', 'utf8'), 'This is a nested file!');
	});

	test('readdir /Nested (mixed case)', () => {
		assert.equal(fs.readdirSync('/Nested').length, 1);
	});
});

await suite('ZIP lazy sync reads #20', () => {
	test('Configure', async () => {
		const buffer = readFileSync(import.meta.dirname + '/files/data.zip');
		const data = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
		await configureSingle({ backend: Zip, data, lazy: true });
	});

	test('first read of an entry does not throw EAGAIN', () => {
		assert.equal(fs.readFileSync('/nested/omg.txt', 'utf8'), 'This is a nested file!');
	});

	_runTests();
});

await using handle = await open(import.meta.dirname + '/files/data.zip');

await suite('ZIP Streaming', () => {
	test('Configure', async () => {
		const stream = handle.readableWebStream() as ReadableStream;
		const { size } = await handle.stat();
		await configureSingle({ backend: Zip, data: fromStream(stream, size) });
	});

	_runTests();
});

await suite('Custom data source', () => {
	test('Configure', async () => {
		const { size } = fstatSync(handle.fd);

		await configureSingle({
			backend: Zip,
			data: {
				size,
				get(offset, length) {
					const data = new Uint8Array(length);
					const read = readSync(handle.fd, data, { position: offset, length });
					assert.equal(read, length);
					return data;
				},
			},
		});
	});

	_runTests();
});

/**
 * Builds a ZIP with stored (uncompressed) entries.
 * A name ending in '/' is written as a directory entry, with the MS-DOS directory attribute set.
 *
 * The fixtures in `tests/files` are generated by `tests/build.ts` from `tests/data`.
 * Git can not track an empty source directory, so that pipeline can not produce an archive
 * with a childless directory entry, and it is built here instead of committing a binary
 * blob `tests/build.ts` could not regenerate.
 *
 * CRCs are left at zero: nothing in `src/zip` validates them.
 */
function buildZip(entries: Record<string, string>): ArrayBuffer {
	const encoder = new TextEncoder();
	const local: Uint8Array[] = [];
	const central: Uint8Array[] = [];

	let offset = 0;

	for (const [rawName, contents] of Object.entries(entries)) {
		const isDirectory = rawName.endsWith('/');
		const name = encoder.encode(rawName);
		const data = encoder.encode(contents);

		const header = new Uint8Array(30 + name.length + data.length);
		const headerView = new DataView(header.buffer);
		headerView.setUint32(0, 0x04034b50, true); // signature
		headerView.setUint16(4, 10, true); // version needed
		headerView.setUint32(18, data.length, true); // compressed size
		headerView.setUint32(22, data.length, true); // uncompressed size
		headerView.setUint16(26, name.length, true);
		header.set(name, 30);
		header.set(data, 30 + name.length);
		local.push(header);

		const entry = new Uint8Array(46 + name.length);
		const entryView = new DataView(entry.buffer);
		entryView.setUint32(0, 0x02014b50, true); // signature
		entryView.setUint16(4, 10, true); // version made by
		entryView.setUint16(6, 10, true); // version needed
		entryView.setUint32(20, data.length, true); // compressed size
		entryView.setUint32(24, data.length, true); // uncompressed size
		entryView.setUint16(28, name.length, true);
		entryView.setUint32(38, isDirectory ? (0o40775 << 16) | 0x10 : 0o100664 << 16, true); // external attributes
		entryView.setUint32(42, offset, true); // local header offset
		entry.set(name, 46);
		central.push(entry);

		offset += header.length;
	}

	const centralSize = central.reduce((sum, entry) => sum + entry.length, 0);

	const eocd = new Uint8Array(22);
	const eocdView = new DataView(eocd.buffer);
	eocdView.setUint32(0, 0x06054b50, true); // signature
	eocdView.setUint16(8, central.length, true); // entries on this disk
	eocdView.setUint16(10, central.length, true); // total entries
	eocdView.setUint32(12, centralSize, true);
	eocdView.setUint32(16, offset, true); // central directory offset

	const zip = new Uint8Array(offset + centralSize + eocd.length);
	let position = 0;
	for (const part of [...local, ...central, eocd]) {
		zip.set(part, position);
		position += part.length;
	}

	return zip.buffer;
}

await suite('ZIP stored empty directories', () => {
	test('Configure', async () => {
		const data = buildZip({
			'keep.txt': 'hi',
			'empty/': '',
			'nested/': '',
			'nested/deep/': '',
			'nested/omg.txt': 'This is a nested file!',
		});
		await configureSingle({ backend: Zip, data });
	});

	test('readdir /', () => {
		assert.deepEqual(fs.readdirSync('/').sort(), ['empty', 'keep.txt', 'nested']);
	});

	test('stat /empty', () => {
		assert.ok(fs.statSync('/empty').isDirectory());
	});

	test('readdirSync /empty', () => {
		assert.deepEqual(fs.readdirSync('/empty'), []);
	});

	test('readdir /empty', async () => {
		assert.deepEqual(await fs.promises.readdir('/empty'), []);
	});

	test('readdir /nested', () => {
		assert.deepEqual(fs.readdirSync('/nested').sort(), ['deep', 'omg.txt']);
	});

	test('readdirSync /nested/deep', () => {
		assert.deepEqual(fs.readdirSync('/nested/deep'), []);
	});

	test('read /empty throws EISDIR', () => {
		assert.throws(() => fs.readFileSync('/empty'), { code: 'EISDIR' });
	});
});
